version: '3.8'

services:
  django:
    container_name: django-webinterface
    build: .  # Uses the Dockerfile in the same directory

    image: nikhiarethiya/django-web:latest
    restart: always

    ports:
      - "9000:8000"  # Expose Django on port 9000, but runs internally on 8000

   # working_dir: /mnt/root_data_storage/users/WebInterface  # Set the working directory to the root

    volumes:
      - /mnt/root_data_storage/users/WebInterface/TrueNASdata:/TrurNASdata:ro       #on TrueNAS /data diretory bind to /mnt/root_data_storage/users/WebInterface/TrueNASdata allo 
      - /mnt/root_data_storage/users/WebInterface/PersistentData:/PersistentData:rw     # Persistent data storage for web interface
      - /mnt/root_data_storage/experiments:/experiments:ro

    environment:
      - PYTHONUNBUFFERED=1                  # Disable output buffering for easier debugging  
      - PYTHONDONTWRITEBYTECODE=1           # Prevent Python from writing .pyc files to disk
      - DEBUG=0                             # Set DEBUG to 0 for production

      - APP_DIR=/
      - CONFIG_DIR=/config/data
      - EXPERIMENTS_DIR=/experiments
      - DATABASE_NAME=/config/data/freenas-v1.db
      
      - ALLOWED_HOSTS=*  # Allow access from all hosts
      - DJANGO_SETTINGS_MODULE=myproject.settings  # Set Django settings module

    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
