version: '3.8'

services:
  web:
    build: .
    image: python:3.10
    container_name: WebInterfaceContainer
    restart: always
    working_dir: /app
    volumes:
      - .:/app    
    ports:
      - "8000:8000"
    command: gunicorn --bind 0.0.0.0:8000 myproject.wsgi:application
